version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_DATABASE: personal_finance
      MYSQL_USER: us3r
      MYSQL_PASSWORD: mypasswd
      MYSQL_ROOT_PASSWORD: 'root' # allow remote access
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
